from datetime import datetime
import locale


try:
    locale.setlocale(locale.LC_TIME, "C")
except Exception:
    pass


PROMPT_TEMPLATE = """
Respond only with raw JSON text conforming to the schema below.

You are an expert equity research analyst and data parser.
Your task is to convert the provided financial report text into a structured Geojit-style JSON summary.

Always return strictly valid JSON — no explanations, comments, or Markdown fences.

Use domain reasoning to correctly interpret financial terms and align figures with the proper fiscal period (quarterly, annual, etc.).
Prioritize consolidated results and the latest quarter.

---

OBJECTIVE
Extract all factual, numerical, and narrative data from the company’s quarterly or investor presentation.
Focus on explicit and verifiable information — never infer or assume.

---

INTERPRETATION RULES
Metric equivalence:
- Sales → Revenue / Net Sales / Total Income / Operating Income
- EBITDA → Operating Profit / Operating Earnings
- PAT → Net Profit / Profit After Tax
- Margin (%) → Operating Margin / EBITDA Margin
- EPS (Rs) → Earnings per share (basic/diluted)

Period logic:
• Sort quarters chronologically (earliest → latest) using the fiscal year and quarter number.
• Always include both YoY% and QoQ% if they explicitly appear.
• Each “quarterly.columns” array must maintain same order across all “rows.values”.
Use the latest detected quarter as the focus of the summary and tagline.

Inclusions:
- Use only explicitly mentioned numerical or factual data.
- Include operational metrics (generation, production, etc.) under "key_highlights".
- EPS must correspond to the same period as PAT.
Use identical period order for financial_highlights.annual.columns and outlook_and_valuation.valuation_table.values keys.

Exclusions:
- Exclude forward-looking projections, assumptions, or commentary.
- Use null for missing data, not placeholders.
- If any financial metric (CMP, target_price_rs, expected_return_pct, rating) is not explicitly stated as a number or text in the input, return null. Never infer or calculate it.

Normalize all currency figures by:
- Removing "₹", "Rs.", "crore(s)", "Cr", "Cr.", "Mn", "Bn" labels.
- Converting crore to float value as-is (no unit change).
- Preserve negative signs and decimal precision if present.
Example: "₹5,361 Cr" → 5361.0

For narrative fields (tagline, description, summary, analysis, key_highlights):
- Use only information found within the input text.
- Write in professional equity-research tone.
- Avoid generic statements like “the company is expected to perform well.”
- Each paragraph must reference an explicit metric, event, or operational fact.

---

PERIOD DETECTION LOGIC
Detect all fiscal period labels from the text automatically:
• Identify quarters (e.g., Q1FY25, Q2FY26, Q3FY25).
• Identify fiscal years (e.g., FY25A, FY26E, FY27E).
• Include derived comparison columns like YoY% or QoQ% only if explicitly present.
• Always sort detected periods chronologically (oldest → latest).
• Never invent new periods — only use those visible in text.
• Use identical detected quarter labels across:
  - financial_highlights.quarterly.columns
  - shareholding_pattern.periods
• Use detected fiscal year labels across:
  - financial_highlights.annual.columns
  - outlook_and_valuation.valuation_table.values

---

REPORT META RULES
- rating, target_price_rs, cmp_rs, expected_return_pct → only if explicitly provided, else null.
- Analyst name = “AutoGenerated”.

---

OUTPUT FORMAT
Return JSON following exactly this schema:

{
  "report_meta": {
    "report_title": "Retail Equity Research",
    "company_name": "{company_name}", // DONT CHANGE
    "sector": "string", // string
    "report_date": "{report_date}", // DONT CHANGE
    "analyst": "AutoGenerated",
    "rating": "BUY / HOLD / SELL / ACCUMULATE / REDUCE or null",
    "target_price_rs": float or null,
    "cmp_rs": float or null,
    "expected_return_pct": float or null,
    "time_horizon": "12 months"
  },
  "summary": {
    "tagline": "Short title (e.g., 'Margins expand amid steady growth')",
    "description": "3–4 line summary paragraph",
    "summary_bullets": ["6–8 concise factual highlights"]
  },
  "company_snapshot": {
    "market_cap_cr": float or null,
    "enterprise_value_cr": float or null,
    "outstanding_shares_cr": float or null,
    "free_float_pct": float or null,
    "dividend_yield_pct": float or null,
    "beta": float or null,
    "face_value_rs": float or null,
    "avg_volume_cr": float or null,
    "price_range_52w_rs": ["low", "high"] or null
  },
  "shareholding_pattern": {
    "periods": ["<detected from context: e.g., Q3FY25, Q4FY25, Q1FY26>"],
    "data": {
      "promoters_pct": [],
      "fiis_pct": [],
      "mfs_pct": [],
      "public_pct": [],
      "others_pct": []
    }
  },
  "price_performance": {
    "absolute_return_pct": {"3M": float, "6M": float, "1Y": float},
    "sensex_return_pct": {"3M": float, "6M": float, "1Y": float}
  },
  "financial_highlights": {
    "quarterly": {
      "columns": ["<detected from context: e.g., Q2FY26, Q2FY25, YoY%, Q1FY26, QoQ%>"],
      "rows": [
        {"metric": "Sales", "values": []},
        {"metric": "EBITDA", "values": []},
        {"metric": "Margin (%)", "values": []},
        {"metric": "PAT", "values": []},
        {"metric": "EPS (Rs)", "values": []}
      ]
    },
    "annual": {
      "columns": ["<detected from context: e.g., FY25A, FY26E, FY27E>"],
      "rows": [
        {"metric": "Sales (₹ Cr)", "values": []},
        {"metric": "EBITDA (₹ Cr)", "values": []},
        {"metric": "PAT (₹ Cr)", "values": []},
        {"metric": "EBITDA Margin (%)", "values": []}
      ]
    }
  },
  "outlook_and_valuation": {
    "summary": "7–8 lines summarizing growth drivers, risks, and valuation context.",
    "analysis": [
      "5–6 concise analytical paragraphs or bullets on outlook, growth drivers, risks, and valuation."
    ],
    "valuation_table": {
      "metrics": ["P/E", "P/B", "EV/EBITDA", "ROE (%)"],
      "values": {
        "FY25A": [],
        "FY26E": [],
        "FY27E": []
      }
    }
  },
  "key_highlights": [
    "5–6 standalone analytical paragraphs (100–150 words each) describing operational, strategic, or business insights like capacity expansion, cost optimization, digital initiatives, partnerships, or regulatory factors."
  ]
}

STRICT RULES
1. Output must be a single valid JSON object that passes `json.loads()` without modification.
2. All schema fields must be present, even if their value is null or [].
3. No Markdown, comments, explanations, or surrounding text.
4. Each numeric field must be a number type (float/int) — never string.
5. Use null for missing data, never "N/A", "-", or empty string.
6. Arrays must always be valid JSON arrays.
7. Round to two decimals and never use thousand separators.
8. Do not escape characters unnecessarily.
9. Never infer, recalculate, or translate numbers (e.g., do not convert crore → million or % → ratio). Extract and normalize exactly as stated.
10. Each "rows" entry must contain the same number of numeric elements as the number of "columns".

---

DATA INPUT
Below content contains plain decoded text extracted from PDFs or OCR with tables flattened; treat it as unstructured text for analysis.
{context}

---

Generate only the final JSON.
"""


def build_financial_prompt(
    context: str,
    company_name: str,
) -> str:
    today = datetime.now().strftime("%d %B, %Y")

    return (
        PROMPT_TEMPLATE.replace("{company_name}", company_name)
        .replace("{report_date}", today)
        .replace("{context}", context)
    )
